name: Build API

on:
  workflow_dispatch:    
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Where Am I?
      run: ls
    - name: Restore dependencies
      run: dotnet restore ./test-api/test-api.csproj
    - name: Build
      run: dotnet build --no-restore ./test-api/test-api.csproj

  call-workflow-passing-data:
    uses: koniin/github-actions/.github/workflows/workflow-B.yml@main
    with:
      message: Hank the tank
    secrets:
      token: ${{ secrets.BOGUS_TOKEN }}
