name: Credit Process dotnet CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from Credit Process

  call-workflow-passing-data:
    needs: build
    uses: koniin/.github/.github/workflows/workflow-B.yml@master
    with:
      message: Hank the tank
