name: Reuseable workflow

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ master ]
    
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      token:
        required: true
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Pass input and secrets to echo
    
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, ${{ inputs.message }}!

      - name: Run a multi-line script
        run: |
          echo ${{ secrets.token }}
          echo ${{ inputs.message }}!
